version: '3.4'

services:
  postgres:
    container_name: auth
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data: # prefered path for store database
    environment:
      POSTGRES_USER: postgres
      POSTGRS_DB: auth
      POSTGRES_PASSWORD: postgres



volumes:
  postgres_data: